
###数据库配置
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/flowable?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ADMIN123
### 核心（流程）
flowable:
  #将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true
  #关闭定时任务JOB（异步执行器）
  process:
    async-executor-activate: false
#服务器配置
server:
  port: 9001